%YAML:1.0

File.version: 1.0 # REQUIRED

Camera.type: "PinHole" # | "KannalaBrandt8" | "Rectified"
  
# ros2 topic echo /zedm/zed_node/right/camera_info
Camera.width: 896
Camera.height: 512

# This value can be configured in the ZED Explorer tool
Camera.fps: 60.0

# stereo baseline (in meters) times fx
# baseline = 0.04907789938876993 m
# fx = 371.1897851022322
# bf = 0.04907789938876993 * 371.1897851022322 = 18.21721
Camera.bf: 18.21721

# Color order of the images Camera.0: BGR,Camera.1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# taken from cam0 in the kalibr output
# focal length in pixels
Camera.fx: 368.82019560326995
Camera.fy: 369.5382255914917

# central point in pixels (principal point)
Camera.cx: 477.66069551985345
Camera.cy: 267.75087100589474

# [-0.08394907413032725, 0.007009491689815073, 0.00030678763098987866, 0.002378055084910331]
# radial distortion coefficients
Camera.k1: -0.08394907413032725
Camera.k2: 0.007009491689815073
# tangential distortion coefficients
Camera.p1: 0.00030678763098987866
Camera.p2: 0.002378055084910331 

# taken from cam1 in the kalibr output
Camera2.fx: 371.1897851022322
Camera2.fy: 372.2493337285106
  
Camera2.cx: 473.10494521498015
Camera2.cy: 268.9200093631702

#  [-0.0800808596617461, 0.002826738256395078, 0.00037452015522339174, 0.004113971771778728]
# radial distortion coefficients
Camera2.k1: -0.0800808596617461
Camera2.k2: 0.002826738256395078
# tangential distortion coefficients
Camera2.p1: 0.00037452015522339174
Camera2.p2: 0.004113971771778728


# Close/Far threshold. Baseline times.
ThDepth: 35.0

# STEREO --------------------------------------------------------------------------------------------
# Stereo.ThDepth: 50.0
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [
    0.99999444, 0.00332512, 0.00023754, 0.04906147,
    -0.00332526, 0.99999429, 0.00060206, -0.0008131,
    -0.00023553, -0.00060285, 0.99999979, 0.00097513,
    0.0, 0.0, 0.0, 1.0]




#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
# TODO: calibrate with `kalibr` tool

LEFT.height: 512
LEFT.width: 896
# found using: ros2 topic echo /zedm/zed_node/left/camera_info
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 477.4671, 258.4399, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
# TODO: can not find this
# BUT IT DOES NOT SEEM TO BE A PROBLEM AS THE ORBSLAM3-ROS2 WRAPPER DOES NOT READ THIS MATRIX. IT READS {LEFT,RIGHT}.{D,K,R,P}
# LEFT.Rf:  !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: f
#    data: [0.999966347530033, -0.001422739138722922, 0.008079580483432283, 0.001365741834644127, 0.9999741760894847, 0.007055629199258132, -0.008089410156878961, -0.007044357138835809, 0.9999424675829176]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 0.0, 477.467193, 258.4399, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 512
RIGHT.width: 896
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 477.4671, 258.4399, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data:
    - 470.0067443847656
    - 0.0
    - 464.2713928222656
    - -29.595149993896484
    - 0.0
    - 477.4671936035156
    - 258.4399719238281
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0


#--------------------------------------------------------------------------------------------
# IMU noise
#--------------------------------------------------------------------------------------------
IMU.Frequency: 800 # Hz
# numbers gotten from calibrating the ZED Mini camera with the `kalibr` tool
IMU.NoiseAcc: 0.0014 # m/s^2/sqrt(Hz)
IMU.NoiseGyro: 8.6e-05 # rad/s/sqrt(Hz)
# It is common practice to increase the random walk standard deviations provided by
# the IMU manufacturer (say multiplying them by 10) to account for unmodelled effects
# and improving the IMU initialization convergence.
IMU.AccWalk: 8.0e-05 # m/s^2.5
IMU.GyroWalk: 2.2e-06 # rad/s^1.5

# Transformation from camera 0 to body-frame (imu)
# numbers gotten from calibrating the ZED Mini camera with the `kalibr` tool
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [
    -0.11725866, -0.20854666, -0.97095762, -0.0001198,
    -0.86021066, 0.50990769, -0.00563608, 0.00066236,
    0.49627414, 0.83456722, -0.23918515, 0.00302998,
    0.0, 0.0, 0.0, 1.0]


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1200 # number of features per image
ORBextractor.scaleFactor: 1.2 # scale factor between levels in the scale pyramid
ORBextractor.nLevels: 12 # number of levels in the scale pyramid
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
# ORBextractor.iniThFAST: 20
ORBextractor.iniThFAST: 10
# ORBextractor.minThFAST: 7
ORBextractor.minThFAST: 3


# Atlas Parameters
# System:
#   LoadAtlasFromFile: "~/Downloads/orbslam3/maps/map0.bin"
#   SaveAtlasToFile: "~/Downloads/orbslam3/maps/map0.bin"

#--------------------------------------------------------------------------------------------
# Viewer Parameters
# These are some parameters related to the ORB-SLAM3 user interface:
#--------------------------------------------------------------------------------------------
# TODO: test this

# Viewer:
  # size in which the KeyFrames are drawn in the map viewer.
Viewer.KeyFrameSize: 0.05
  # line width of the KeyFrame drawing.
Viewer.KeyFrameLineWidth: 1
  # line width of the covisibility graph.
Viewer.GraphLineWidth: 0.9
  # size of the MapPoint drawing.
Viewer.PointSize: 5
  # size in which the current camera is drawn in the map viewer
Viewer.CameraSize: 0.08
  # line width of the current camera drawing.
Viewer.CameraLineWidth: 3
  # starting view point of the map viewer.
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
  # OPTIONAL
Viewer.imageViewScale: 1.0