%YAML:1.0

File.version: 1.0 # REQUIRED

Camera.type: "PinHole" # | "KannalaBrandt8" | "Rectified"
  
# focal length in pixels
# Camera.fx: 699.72
Camera.fx: 371.1897851022322
# Camera.fy: 699.975
Camera.fy: 372.2493337285106
  
# central point in pixels (principal point)
# Camera.cx: 653.9
Camera.cx: 477.66069551985345
# Camera.cy: 335.677
Camera.cy: 267.75087100589474

# radial distortion coefficients
Camera.k1: -0.173726
Camera.k2: 0.0271728
Camera.k3: 0
# tangential distortion coefficients
Camera.p1: 0.000257732
Camera.p2: -0.00026035

# found using `ZED_Explorer` tool
#Camera.width: 2560
#Camera.height: 720
# found using 
# ros2 topic echo /zedm/zed_node/right/camera_info
Camera.width: 896
Camera.height: 512

# This value can be configured in the ZED Explorer tool
Camera.fps: 60.0

# stereo baseline (in meters) times fx
# baseline = 62.9452 mm = 0.0629452 m
# fx = 371.1897851022322
# bf = 0.0629452 * 371.1897851022322 = 23.333
Camera.bf: 23.333

# Color order of the images Camera.0: BGR,Camera.1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


# Close/Far threshold. Baseline times.
ThDepth: 35.0

# Transformation from camera 0 to body-frame (imu)
# numbers gotten from calibrating the ZED Mini camera with the `kalibr` tool
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.11725866, -0.86021066, 0.49627414, -0.00094798,
        -0.20854666, 0.50990769, 0.83456722, -0.00289144,
        -0.97095762, -0.00563608, -0.23918515, 0.00061214,
         0.0, 0.0, 0.0, 1.0]



#  data: [0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
  #        0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
  #       -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
  #        0.0, 0.0, 0.0, 1.0]

#--------------------------------------------------------------------------------------------
# Stereo Rectification. Only if you need to pre-rectify the images.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------
# TODO: calibrate with `kalibr` tool

LEFT.height: 896
LEFT.width: 512
# found using: ros2 topic echo /zedm/zed_node/left/camera_info
LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 477.4671, 258.4399, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
# TODO: can not find this
# BUT IT DOES NOT SEEM TO BE A PROBLEM AS THE ORBSLAM3-ROS2 WRAPPER DOES NOT READ THIS MATRIX. IT READS {LEFT,RIGHT}.{D,K,R,P}
# LEFT.Rf:  !!opencv-matrix
#    rows: 3
#    cols: 3
#    dt: f
#    data: [0.999966347530033, -0.001422739138722922, 0.008079580483432283, 0.001365741834644127, 0.9999741760894847, 0.007055629199258132, -0.008089410156878961, -0.007044357138835809, 0.9999424675829176]
LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 0.0, 477.467193, 258.4399, 0.0, 0.0, 0.0, 1.0, 0.0]

RIGHT.height: 896
RIGHT.width: 512
RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [470.006, 0.0, 464.271, 0.0, 477.4671, 258.4399, 0.0, 0.0, 1.0]
RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data:
    - 470.0067443847656
    - 0.0
    - 464.2713928222656
    - -29.595149993896484
    - 0.0
    - 477.4671936035156
    - 258.4399719238281
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0


#--------------------------------------------------------------------------------------------
# IMU noise
#--------------------------------------------------------------------------------------------
IMU.Frequency: 800 # Hz
# numbers gotten from calibrating the ZED Mini camera with the `kalibr` tool
# IMU.NoiseAcc: 0.0014 # m/s^2/sqrt(Hz)
# IMU.NoiseGyro: 8.6e-05 # rad/s/sqrt(Hz)
# It is common practice to increase the random walk standard deviations provided by
# the IMU manufacturer (say multiplying them by 10) to account for unmodelled effects
# and improving the IMU initialization convergence.
# IMU.AccWalk: 8.0e-05 # m/s^2.5
# IMU.GyroWalk: 2.2e-06 # rad/s^1.5

# try with very small values e.g. 10e-8
IMU.NoiseAcc: 10e-8
IMU.NoiseGyro: 10e-8
IMU.AccWalk: 10e-8
IMU.GyroWalk: 10e-8



#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1200 # number of features per image
ORBextractor.scaleFactor: 1.2 # scale factor between levels in the scale pyramid
ORBextractor.nLevels: 8 # number of levels in the scale pyramid
  # Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
  # Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
  # You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7


# Atlas Parameters
# System:
#   LoadAtlasFromFile: "~/Downloads/orbslam3/maps/map0.bin"
#   SaveAtlasToFile: "~/Downloads/orbslam3/maps/map0.bin"

#--------------------------------------------------------------------------------------------
# Viewer Parameters
# These are some parameters related to the ORB-SLAM3 user interface:
#--------------------------------------------------------------------------------------------
# TODO: test this

# Viewer:
  # size in which the KeyFrames are drawn in the map viewer.
Viewer.KeyFrameSize: 0.15
  # line width of the KeyFrame drawing.
Viewer.KeyFrameLineWidth: 1
  # line width of the covisibility graph.
Viewer.GraphLineWidth: 0.9
  # size of the MapPoint drawing.
Viewer.PointSize: 2
  # size in which the current camera is drawn in the map viewer
Viewer.CameraSize: 0.10
  # line width of the current camera drawing.
Viewer.CameraLineWidth: 3
  # starting view point of the map viewer.
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
  # OPTIONAL
Viewer.imageViewScale: 1.0