%YAML:1.0
---
# NOTE: Settings read from these files
# https://github.com/url-kaist/dynaVINS/blob/main/config/realsense_d455/realsense_stereo_imu_config_mono.yaml

File.version: 1.0 # REQUIRED

Camera.type: "PinHole" # | "KannalaBrandt8" | "Rectified"

Camera.width: 640
Camera.height: 480

# UNKNOWN
Camera.fps: 20.0

# UNKNOWN
Camera.RGB: 1

# stereo baseline (in meters) times fx
# UNKNOWN (just a guess)
# fx = 391.3730335124379
# bf = 0.05 * fx = 0.05 * 391.3730335124379 = 19.568651675621895
Camera.bf: 19.568651675621895

## Projection parameters for cam0
# focal length in pixels
Camera.fx: 391.3730335124379
Camera.fy: 390.9174606492363

# central point in pixels (principal point)
Camera.cx: 319.3410681604872
Camera.cy: 241.67586303602286

# radial distortion coefficients
Camera.k1: 0.008042263604146338
Camera.k2: -0.004006785115307955

# tangential distortion coefficients
Camera.p1: -0.0001136308613068791
Camera.p2: 0.0005968909268653054

## Projection parameters for cam1
# focal length in pixels
Camera2.fx: 392.2494728318245
Camera2.fy: 391.7709976125993

# central point in pixels (principal point)
Camera2.cx: 316.50239262676575
Camera2.cy: 242.05219142504689

# radial distortion coefficients
Camera2.k1: 0.00977423853451956
Camera2.k2: -0.0074722179966595975
# tangential distortion coefficients
Camera2.p1: 0.0002994015320500702
Camera2.p2: -0.00022518799139296098

# Close/Far threshold. Baseline times.
# UNKNOWN (just a guess)
ThDepth: 35.0

# STEREO --------------------------------------------------------------------------------------------
# Stereo.ThDepth: 50.0
# UNKNOWN (setting to unity)
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [
      1.0, 0.0, 0.0, 0.0,
      0.0, 1.0, 0.0, 0.05,
      0.0, 0.0, 1.0, 0.0,
      0.0, 0.0, 0.0, 1.0
    ]

#--------------------------------------------------------------------------------------------
# IMU noise
#--------------------------------------------------------------------------------------------
# UNKNOWN
IMU.Frequency: 200 # Hz
# IMU.NoiseAcc: 0.2 # accelerometer measurement noise standard deviation.
# IMU.NoiseGyro: 0.05 # gyroscope measurement noise standard deviation.
# It is common practice to increase the random walk standard deviations provided by
# the IMU manufacturer (say multiplying them by 10) to account for unmodelled effects
# and improving the IMU initialization convergence.
# IMU.AccWalk: 0.02 # accelerometer bias random work noise standard deviation.
# IMU.GyroWalk: 4.0e-5 # gyroscope bias random work noise standard deviation.

# https://github.com/url-kaist/dynaVINS/blob/f888921beb55ddf06590d8537744a4dfcbddff70/config/realsense_d455/realsense_stereo_imu_config_stereo.yaml#L82-L86
IMU.NoiseAcc: 0.278568031016
IMU.NoiseGyro: 0.024937606912
IMU.AccWalk: 0.000827382177682
IMU.GyroWalk: 1.71512255197e-05

IMU.fastInit: 1

IMU.InsertKFsWhenLost: 1

# Transformation from camera 0 to body-frame (imu)
# IMU.T_b_c1: !!opencv-matrix

# Tbc: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: f
#   data: [
#       -0.11725866, -0.20854666, -0.97095762, -0.0001198,
#       -0.86021066, 0.50990769, -0.00563608, 0.00066236,
#       0.49627414, 0.83456722, -0.23918515, 0.00302998,
#       0.0, 0.0, 0.0, 1.0
#     ]

# Transformation from body-frame (imu) to left camera
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [ 0.99998534, -0.00438068,  0.00318378,  0.06154326,
       0.00437405,  0.99998826,  0.0020868,   0.00394544 ,
        -0.00319288, -0.00207284,  0.99999275,  0.02056234,
       0., 0., 0., 1. ]

Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [  0.99995065, -0.00448684,  0.00886397, -0.03341319,
       0.00447312,  0.99998877,  0.00156799,  0.00350357 ,
        -0.00887091, -0.00152826,  0.99995948,  0.02122639,
       0., 0., 0., 1. ]

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

ORBextractor.nFeatures: 1200 # number of features per image
ORBextractor.scaleFactor: 1.2 # scale factor between levels in the scale pyramid
ORBextractor.nLevels: 12 # number of levels in the scale pyramid
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
# ORBextractor.iniThFAST: 20
ORBextractor.iniThFAST: 10
# ORBextractor.minThFAST: 7
ORBextractor.minThFAST: 3

#--------------------------------------------------------------------------------------------
# Viewer Parameters
# These are some parameters related to the ORB-SLAM3 user interface:
#--------------------------------------------------------------------------------------------
# size in which the KeyFrames are drawn in the map viewer.
Viewer.KeyFrameSize: 0.05
# line width of the KeyFrame drawing.
Viewer.KeyFrameLineWidth: 1
# line width of the covisibility graph.
Viewer.GraphLineWidth: 0.9
# size of the MapPoint drawing.
Viewer.PointSize: 5
# size in which the current camera is drawn in the map viewer
Viewer.CameraSize: 0.08
# line width of the current camera drawing.
Viewer.CameraLineWidth: 3
# starting view point of the map viewer.
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
# OPTIONAL
Viewer.imageViewScale: 1.0
